name: web

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Restore Docker cache
        uses: actions/cache@v2
        env:
          cache-name: docker
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate tags
        id: generate-tags
        uses: hulloitskai/generate-docker-tags-action@v0.2.1
        with:
          repo: hulloitskai/home-web
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web/
          push: true
          tags: ${{ steps.generate-tags.outputs.tags }}
          cache-from: |
            type=local,src=/tmp/.docker-cache
          cache-to: |
            type=local,dest=/tmp/.docker-cache,mode=max
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Discover Yarn cache dir
        id: discover-yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Yarn cache
        uses: actions/cache@v2
        env:
          cache-name: yarn
        with:
          path: ${{ steps.discover-yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ env.cache-name }}
      - name: Bootstrap
        working-directory: web
        run: yarn
      - name: Lint
        working-directory: web
        run: yarn lint
